logging:
  level:
    com.example.peer: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://peer-mysql:3306/peer
    username: root
    password: 1236
  security:
    jwt:
      secret-key: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
    oauth2:
      client:
        registration:
          google:
            client-id: 46108256183-5md30gf6snl3l5rjlt105o9bm1t99shm.apps.googleusercontent.com
            redirect-uri: http://localhost:8080/oauth2/google/callback
            client-secret: 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
            scope: # google API의 범위 값
              - profile
              - email

          kakao:
            client-id: af328857e9435a806029369bd5abdb36
            # client-secret: ${KAKAO_SECRET}
            redirect-uri: http://localhost:8080/oauth2/kakao/callback
            client-secret: i7WtsEOrVaCtWCmLhombzmUtYycAUs04
            client-authentication-method: client_secret_post
            # kakao는 인증 토큰 발급 요청 메서드가 post이다. (최근 버전에는 작성 방법이 이렇게 바뀌었다.)
            authorization-grant-type: authorization_code
            scope: # kakao 개인 정보 동의 항목 설정의 ID 값
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao
          naver:
            client-id: LzElbp_ztJhn0Mwx_A9p
            # client-secret: ${KAKAO_SECRET}
            redirect-uri: http://localhost:8080/oauth2/naver/callback
            client-secret: Heyos2A6PH
            client-authentication-method: client_secret_post
            # kakao는 인증 토큰 발급 요청 메서드가 post이다. (최근 버전에는 작성 방법이 이렇게 바뀌었다.)
            authorization-grant-type: authorization_code
            scope: # kakao 개인 정보 동의 항목 설정의 ID 값
              - profile_nickname
              - profile_image
              - account_email
            client-name: naver


        # kakao provider 설정
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 유저 정보 조회 시 반환되는 최상위 필드명으로 해야 한다.

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 return해줌.
            # (value에는 getAttributes()한 값들이 들어가있음)