name: build-peer-server
	
  on:
    push:
      branches: [ main ]
	
  jobs:
    build:
      runs-on: ubuntu-latest
	
      steps:
      - uses: actions/checkout@v2
	
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: haeunseo/peer-server:latest